#pragma once
void Algoritm1();
void Algoritm2();
void Algoritm3();
void Algoritm4();
void Algoritm5();
void Algoritm6();
void Algoritm7();
void Algoritm8();
void Algoritm9();
void Algoritm10();